// Barrel exports for icons — ported 1:1 from cas-client-platform (libs/shared/icons)
// to keep tenant-management pixel-matched to the real product's icon set.
export { default as IconAdd } from './icon-add';
export { default as IconArrowLeft } from './icon-arrow-left';
export { default as IconArrowRight } from './icon-arrow-right';
export { default as IconAttachMoney } from './icon-attach-money';
export { default as IconCurrency } from './icon-attach-money';
export { default as IconBellBing } from './icon-bell-bing';
export { default as IconCaretsDown } from './icon-carets-down';
export { default as IconChevronDown } from './icon-chevron-down';
export { default as IconDelete } from './icon-delete';
export { default as IconDoubleArrowLeft } from './icon-double-arrow-left';
export { default as IconDoubleArrowRight } from './icon-double-arrow-right';
export { default as IconDownArrow } from './icon-down-arrow';
export { default as IconEdit } from './icon-edit';
export { IconError } from './icon-error';
export { default as IconFilter } from './icon-filter';
export { default as IconGrid } from './icon-grid';
export { IconInfo } from './icon-info';
export { default as IconInfoCircle } from './icon-info-circle';
export { default as IconLaptop } from './icon-laptop';
export { default as IconLockDots } from './icon-lock-dots';
export { default as IconLogout } from './icon-logout';
export { default as IconMail } from './icon-mail';
export { default as IconMenuUsers } from './icon-menu-users';
export { default as IconMenuWidgets } from './icon-menu-widgets';
export { default as IconMenu } from './icon-menu';
export { default as IconMoon } from './icon-moon';
export { default as IconMore } from './icon-more';
export { default as IconNoData } from './icon-no-data';
export { default as ChartSlashIcon } from './icon-no-data';
export { default as IconPlus } from './icon-plus';
export { default as IconSearch } from './icon-search';
export { default as IconSparkle } from './icon-sparkle';
export { default as SuggestedLogo } from './icon-sparkle';
export { IconSuccess } from './icon-success';
export { default as IconSun } from './icon-sun';
export { default as IconUpArrow } from './icon-up-arrow';
export { default as IconUpDown } from './icon-up-down';
export { default as UpDownIcon } from './icon-up-down';
export { default as IconUser } from './icon-user';
export { default as IconUsers } from './icon-users';
export { default as IconUsersGroup } from './icon-users';
export { IconWarning } from './icon-warning';
export { default as IconWatch } from './icon-watch';
export { default as WatchIcon } from './icon-watch';
export { default as IconXCircle } from './icon-x-circle';
export { default as IconX } from './icon-x';
export { default as KebabIcon } from './icon-kebab';

export { default as IconAdministration } from './icon-administration';
export { default as IconLoading } from './icon-loading';
export { CheckCircleIcon } from './icon-check-circle';
export { ClockIcon } from './icon-pending';
export { XCircleIcon } from './icon-failed';
export { ServerIcon } from './icon-server';
export { default as IconDownload } from './icon-download';
export { default as IconCheck } from './icon-check';
